### ISSUE TITLE
This repo requires a policy for submission evaluations and more administrators

### ISSUE THREAD

**Issue by Dowwie** [ctjhoa/rust-learning#126]
This repo lacks a policy stating guidelines for submissions.  ctjhoa is filtering based on personal discretion.  That isn't suitable for a community effort such as what this repo entails.

**Comment by eliukblau** [comment]
Yeah, because this is his personal effort. For now. See contributors graph of this repo. 280+ commits from ctjhoa. Maybe it's time to create a policy, maybe not. but, for now, is mainly a personal effort. - https://github.com/ctjhoa/rust-learning/graphs/contributors

**Comment by ctjhoa** [comment]
Check #124 for the whole story

**Comment by ctjhoa** [comment]
We now have contribution guidelines. d8f651e9daf4d8d87f77a04dd35da1367a7ecdd7
I close this issue.
