### ISSUE TITLE
My FizzBuzz article is *not* a language comparison

### ISSUE THREAD

**Issue by chris-morgan** [ctjhoa/rust-learning#15]
My article “Why your first FizzBuzz implementation may not work: an exploration into some initially surprising but great parts of Rust (though you still might not like them)” is currently listed in “Comparison with Other Languages” with the title “Fizzbuzz: Rust vs Python”. This is not an accurate title or location. The Python code included in the article is *completely* secondary and could be removed very easily with no harm to the article. It is purely there for simple reference as something people are more likely to be familiar with.

**Comment by ctjhoa** [comment]
@chris-morgan Yeah you're right. I'm not quite sure where to put it. Maybe the "Rust in practice" is more accurate. What do you think about that ?

**Comment by ctjhoa** [comment]
I take this as yes ! Thanks for the report anyway
