### ISSUE TITLE
Simplify Rust Book links

### ISSUE THREAD

**Issue by rfdonnelly** [ctjhoa/rust-learning#152]
I find the Rust Book links to be noisy.  It is not immediately clear which a new rustacean should reach for.  They all have a star so that doesn't help.  The top entry is the 1st edition which isn't the one a new rustacean should reach for.  New rustaceans should be directed toward the current edition.

## Current

* :star: [The Rust Programming Language 1st edition](https://doc.rust-lang.org/1.30.0/book/first-edition/) - [repo](https://github.com/rust-lang/book/tree/master/first-edition)
* :star: [The Rust Programming Language 2nd edition](https://doc.rust-lang.org/1.30.0/book/second-edition/) - [repo](https://github.com/rust-lang/book/tree/master/second-edition) ([Paper edition](https://www.nostarch.com/Rust))
* :star: [The Rust Programming Language 2018 edition](https://doc.rust-lang.org/1.30.0/book/2018-edition/) - [repo](https://github.com/rust-lang/book/tree/master/2018-edition)
* :star: [The Rust Programming Language current version](https://doc.rust-lang.org/stable/book/) - [repo](https://github.com/rust-lang/book)

## Alternative 1

Reverse the order.  The current edition is now the first.  This is still pretty noisy.  It still takes effort to consider all the options because they all look very similar.

* :star: [The Rust Programming Language current version](https://doc.rust-lang.org/stable/book/) - [repo](https://github.com/rust-lang/book)
* :star: [The Rust Programming Language 2018 edition](https://doc.rust-lang.org/1.30.0/book/2018-edition/) - [repo](https://github.com/rust-lang/book/tree/master/2018-edition)
* :star: [The Rust Programming Language 2nd edition](https://doc.rust-lang.org/1.30.0/book/second-edition/) - [repo](https://github.com/rust-lang/book/tree/master/second-edition) ([Paper edition](https://www.nostarch.com/Rust))
* :star: [The Rust Programming Language 1st edition](https://doc.rust-lang.org/1.30.0/book/first-edition/) - [repo](https://github.com/rust-lang/book/tree/master/first-edition)

## Alternative 2

Add an icon to represent recommended content.  Still noisy but the current edition now stands out.

* :100: :star: [The Rust Programming Language current version](https://doc.rust-lang.org/stable/book/) - [repo](https://github.com/rust-lang/book)
* :star: [The Rust Programming Language 2018 edition](https://doc.rust-lang.org/1.30.0/book/2018-edition/) - [repo](https://github.com/rust-lang/book/tree/master/2018-edition)
* :star: [The Rust Programming Language 2nd edition](https://doc.rust-lang.org/1.30.0/book/second-edition/) - [repo](https://github.com/rust-lang/book/tree/master/second-edition) ([Paper edition](https://www.nostarch.com/Rust))
* :star: [The Rust Programming Language 1st edition](https://doc.rust-lang.org/1.30.0/book/first-edition/) - [repo](https://github.com/rust-lang/book/tree/master/first-edition)

## Alternative 3

Reduce to single line.  Less noise but still have more than necessary.

* :star: [The Rust Programming Language](https://doc.rust-lang.org/stable/book/) - [[2018 edition](https://doc.rust-lang.org/1.30.0/book/2018-edition)] [[2nd edition](https://doc.rust-lang.org/1.30.0/book/second-edition)] [[1st edition](https://doc.rust-lang.org/1.30.0/book/first-edition)] 
[[1st edition book](https://www.nostarch.com/Rust)] [[repo](https://github.com/rust-lang/book)]

## Alternative 4

Remove old editions.

* :star: [The Rust Programming Language](https://doc.rust-lang.org/stable/book/) - [[repo](https://github.com/rust-lang/book)]

## Recommendation

Implement alternative #4.  Showing all editions adds confusion which slows learning.  The old editions are less for learning and more for reference.  If you are looking for an older edition you probably aren't going to the rust-learning repo to find it.

**Comment by ctjhoa** [comment]
I agree with you, I will remove all legacy versions of TRPL.
