### ISSUE TITLE
The Rustonomicon

### ISSUE THREAD

**Issue by gwenn** [ctjhoa/rust-learning#20]
Hello,
I am not sure but I think that the following dead link:
```md
* [official] [The Advanced Rust Programming Language](https://doc.rust-lang.org/nightly/adv-book/)
```
has been replaced by:
```md
* [official] [The Rustonomicon - The Dark Arts of Advanced and Unsafe Rust Programming](https://doc.rust-lang.org/nightly/nomicon/)
```
Regards.

**Comment by ctjhoa** [comment]
Hi,
Yeah you're right ! Here is [the news](http://this-week-in-rust.org/blog/2015/08/03/this-week-in-rust-90/#whats-cooking-on-nightly) I missed.
Thanks for the report.
