### ISSUE TITLE
where are you From::from

### ISSUE THREAD

**Issue by llogiq** [ctjhoa/rust-learning#33]
May I humbly suggest you add a link to another blog post of mine: http://llogiq.github.io/2015/11/27/from-into.html

At least carols10cents found it enlightening. If you like, I can push a PR, otherwise feel free to close without ceremony.

**Comment by ctjhoa** [comment]
Thanks for the report I must have missed it.
@llogiq I have also added you to `Famous Rustacean Bloggers` as you are a good community contributor.

**Comment by llogiq** [comment]
Whoa, I didn't consider myself famous. :smile: Thank you.
