### ISSUE TITLE
Add CIS 198 from University of Pennsylvania to the list

### ISSUE THREAD

**Issue by sunu** [ctjhoa/rust-learning#42]
The course material is online at http://cis198-2016s.github.io/
I would send a PR, but I have no idea which section this belongs in.

**Comment by ctjhoa** [comment]
Here is another one http://users.eecs.northwestern.edu/~jesse/course/eecs395/ but I don't know if I'll create a new sections for courses.
I don't want to have all universities in a world on rust-learning so maybe use the github wiki section for that.
Tell me what you think.

**Comment by sunu** [comment]
What I like about the UPenn course is the slides . They are really well made. Helped me get a quick but detailed overview of the language. Here are the [slides from the first class](http://cis198-2016s.github.io/slides/00/#3) for example.
So may be you can put them under a slides section or a miscellaneous resources section.

**Comment by edunham** [comment]
added to the "tutorials and workshop materials" section in https://github.com/ctjhoa/rust-learning/pull/85

**Comment by dumindu** [comment]
This is one of the great resource to learn Rust. Why can't we add this soon. This is almost 1 year old suggestion.

**Comment by ctjhoa** [comment]
@dumindu IMO I don't find those slides so useful compare to links already present. As @sunu was the only one to vote for those links until last week, I didn't took the time to add them. Anyway I merge @edunham's PR. Thanks.
