### ISSUE TITLE
Add Italian section

### ISSUE THREAD

**Issue by carlomilanesi** [ctjhoa/rust-learning#64]
Please add an Italian language section, with two resources:

- [Il linguaggio di programmazione Rust](https://carlomilanesi.github.io/linguaggio-rust/) This is the complete translation of the official book "The Rust Programming Language".
- [Programmazione in Rust passo per passo](https://carlomilanesi.gitbooks.io/programmazione-in-rust-passo-per-passo/content/) This is an original tutorial. It is a work in progress, but already useful.

**Comment by ctjhoa** [comment]
Can you make a PR?

**Comment by carlomilanesi** [comment]
Done
