### ISSUE TITLE
Cleanup old/dead links

### ISSUE THREAD

**Issue by ctjhoa** [ctjhoa/rust-learning#97]
Following [this conversation](#87) the goal of this issue is to do some cleanup in order to detect old or dead resources.

Feel free to ask a removing here or define a limit for considering old links.

**Comment by kestess** [comment]
one of the old links:
⭐️ OReilly's Programming in Rust - Jim Blandy
https://github.com/ctjhoa/rust-learning#videos

**Comment by DineshMv** [comment]
I'd like to help with this issue. Found some dead links.

**Comment by cento** [comment]
@DineshMv and @kestess thank you very much, feel free to fork the repo and use the pull request mechanism!

**Comment by ctjhoa** [comment]
@kestess I've replace `OReilly's Programming in Rust - Jim Blandy` with https://www.youtube.com/watch?v=wXoY91w4Agk
